type_colors = {
	'normal': '#A8A77A',
	'feu': '#EE8130',
	'eau': '#6390F0',
	'electrik': '#F7D02C',
	'plante': '#7AC74C',
	'glace': '#96D9D6',
	'combat': '#C22E28',
	'poison': '#A33EA1',
	'sol': '#E2BF65',
	'vol': '#A98FF3',
	'psy': '#F95587',
	'insecte': '#A6B91A',
	'roche': '#B6A136',
	'spectre': '#735797',
	'dragon': '#6F35FC',
	'ténèbres': '#705746',
	'acier': '#B7B7CE',
	'fée': '#D685AD',
}

dico_pokemon = {
    "001": {
        "name": "Bulbizarre",
        "types": ["plante", "poison"],
        "size": "0.7",
        "weight": "6.9",
        "species": "Pokémon Graine",
        "description": "Une graine est plantée sur son dos à la naissance. Elle grandit lentement en captant la lumière.",
        "sprite_path": "images/sprites/1.gif",
        "footprint_path": "images/footprints/1.png",
    },
    "002": {
        "name": "Herbizarre",
        "types": ["plante", "poison"],
        "size": "1.0",
        "weight": "13.0",
        "species": "Pokémon Graine",
        "description": "Le bulbe sur son dos commence à fleurir lorsqu’il absorbe suffisamment de nutriments.",
        "sprite_path": "images/sprites/2.gif",
        "footprint_path": "images/footprints/2.png",
    },
    "003": {
        "name": "Florizarre",
        "types": ["plante", "poison"],
        "size": "2.0",
        "weight": "100.0",
        "species": "Pokémon Graine",
        "description": "La grande fleur sur son dos absorbe la lumière pour alimenter ses puissantes capacités.",
        "sprite_path": "images/sprites/3.gif",
        "footprint_path": "images/footprints/3.png",
    },
    "004": {
        "name": "Salamèche",
        "types": ["feu"],
        "size": "0.6",
        "weight": "8.5",
        "species": "Pokémon Lézard",
        "description": "La flamme sur sa queue brûle selon sa santé et son humeur.",
        "sprite_path": "images/sprites/4.gif",
        "footprint_path": "images/footprints/4.png",
    },
    "005": {
        "name": "Reptincel",
        "types": ["feu"],
        "size": "1.1",
        "weight": "19.0",
        "species": "Pokémon Flamme",
        "description": "Extrêmement agressif, il utilise sa queue embrasée pour frapper ses adversaires.",
        "sprite_path": "images/sprites/5.gif",
        "footprint_path": "images/footprints/5.png",
    },
    "006": {
        "name": "Dracaufeu",
        "types": ["feu", "vol"],
        "size": "1.7",
        "weight": "90.5",
        "species": "Pokémon Flamme",
        "description": "Il peut voler haut dans le ciel en crachant des flammes ardentes.",
        "sprite_path": "images/sprites/6.gif",
        "footprint_path": "images/footprints/6.png",
    },
    "007": {
        "name": "Carapuce",
        "types": ["eau"],
        "size": "0.5",
        "weight": "9.0",
        "species": "Pokémon Petite Tortue",
        "description": "Quand il est menacé, il se réfugie dans sa carapace pour se protéger.",
        "sprite_path": "images/sprites/7.gif",
        "footprint_path": "images/footprints/7.png",
    },
    "008": {
        "name": "Carabaffe",
        "types": ["eau"],
        "size": "1.0",
        "weight": "22.5",
        "species": "Pokémon Tortue",
        "description": "Ses puissants jets d’eau sortent de ses canons dorsaux.",
        "sprite_path": "images/sprites/8.gif",
        "footprint_path": "images/footprints/8.png",
    },
    "009": {
        "name": "Tortank",
        "types": ["eau"],
        "size": "1.6",
        "weight": "85.5",
        "species": "Pokémon Carapace",
        "description": "Ses canons d’eau hypertrophiés lui permettent d’écraser ses opposants.",
        "sprite_path": "images/sprites/9.gif",
        "footprint_path": "images/footprints/9.png",
    },
}
