type_colors = {
	'normal': '#A8A77A',
	'feu': '#EE8130',
	'eau': '#6390F0',
	'électrik': '#F7D02C',
	'plante': '#7AC74C',
	'glace': '#96D9D6',
	'combat': '#C22E28',
	'poison': '#A33EA1',
	'sol': '#E2BF65',
	'vol': '#A98FF3',
	'psy': '#F95587',
	'insecte': '#A6B91A',
	'roche': '#B6A136',
	'spectre': '#735797',
	'dragon': '#6F35FC',
	'ténèbres': '#705746',
	'acier': '#B7B7CE',
	'fée': '#D685AD',
}

dico_pokemon = {

    '001': {
        'name': 'Bulbizarre',
        'types': ['plante', 'poison'],
        'size': '0.7',
        'weight': '6.9',
        'species': 'Pokémon Graine',
        'description': "Une graine est plantée sur son dos depuis la naissance. Elle grossit lentement.",
        'sprite_path': 'images/sprites/1.gif',
        'footprint_path': 'images/footprints/1.png',
        'cry_path': 'sounds/cries/1.ogg',
    },

    '002': {
        'name': 'Herbizarre',
        'types': ['plante', 'poison'],
        'size': '1.0',
        'weight': '13.0',
        'species': 'Pokémon Graine',
        'description': "Le bulbe sur son dos grandit en puisant son énergie dans les rayons du soleil.",
        'sprite_path': 'images/sprites/2.gif',
        'footprint_path': 'images/footprints/2.png',
        'cry_path': 'sounds/cries/2.ogg',
    },

    '003': {
        'name': 'Florizarre',
        'types': ['plante', 'poison'],
        'size': '2.0',
        'weight': '100.0',
        'species': 'Pokémon Graine',
        'description': "Sa fleur s’épanouit lorsqu’elle absorbe l’énergie solaire. Elle répand alors un parfum apaisant.",
        'sprite_path': 'images/sprites/3.gif',
        'footprint_path': 'images/footprints/3.png',
        'cry_path': 'sounds/cries/3.ogg',
    },

    '004': {
        'name': 'Salamèche',
        'types': ['feu'],
        'size': '0.6',
        'weight': '8.5',
        'species': 'Pokémon Lézard',
        'description': "La flamme au bout de sa queue indique son humeur et son état de santé.",
        'sprite_path': 'images/sprites/4.gif',
        'footprint_path': 'images/footprints/4.png',
        'cry_path': 'sounds/cries/4.ogg',
    },

    '005': {
        'name': 'Reptincel',
        'types': ['feu'],
        'size': '1.1',
        'weight': '19.0',
        'species': 'Pokémon Flamme',
        'description': "Il se bat avec acharnement en fouettant l’air de sa queue enflammée.",
        'sprite_path': 'images/sprites/5.gif',
        'footprint_path': 'images/footprints/5.png',
        'cry_path': 'sounds/cries/5.ogg',
    },

    '006': {
        'name': 'Dracaufeu',
        'types': ['feu', 'vol'],
        'size': '1.7',
        'weight': '90.5',
        'species': 'Pokémon Flamme',
        'description': "Il crache des flammes brûlantes capables de faire fondre n’importe quoi.",
        'sprite_path': 'images/sprites/6.gif',
        'footprint_path': 'images/footprints/6.png',
        'cry_path': 'sounds/cries/6.ogg',
    },

    '007': {
        'name': 'Carapuce',
        'types': ['eau'],
        'size': '0.5',
        'weight': '9.0',
        'species': 'Pokémon Minitortue',
        'description': "Sa carapace lui sert de protection. Il s’y réfugie lorsqu’il est en danger.",
        'sprite_path': 'images/sprites/7.gif',
        'footprint_path': 'images/footprints/7.png',
        'cry_path': 'sounds/cries/7.ogg',
    },

    '008': {
        'name': 'Carabaffe',
        'types': ['eau'],
        'size': '1.0',
        'weight': '22.5',
        'species': 'Pokémon Tortue',
        'description': "Il contrôle l’écoulement de l’eau grâce à sa queue touffue.",
        'sprite_path': 'images/sprites/8.gif',
        'footprint_path': 'images/footprints/8.png',
        'cry_path': 'sounds/cries/8.ogg',
    },

    '009': {
        'name': 'Tortank',
        'types': ['eau'],
        'size': '1.6',
        'weight': '85.5',
        'species': 'Pokémon Carapace',
        'description': "Ses canons projettent des jets d’eau capables de percer de l’acier.",
        'sprite_path': 'images/sprites/9.gif',
        'footprint_path': 'images/footprints/9.png',
        'cry_path': 'sounds/cries/9.ogg',
    },
    
    "010": {
        "name": "Chenipan",
        "types": ["insecte"],
        "size": "0.3",
        "weight": "2.9",
        "species": "Pokémon Ver",
        "description": "Pour se protéger, il libère une puanteur horrible depuis les antennes sur sa tête pour repousser ses ennemis.",
        "sprite_path": "images/sprites/10.gif",
        "footprint_path": "images/footprints/10.png",
        "cry_path": "sounds/cries/10.ogg",
    },
    "011": {
        "name": "Chrysacier",
        "types": ["insecte"],
        "size": "0.7",
        "weight": "9.9",
        "species": "Pokémon Cocon",
        "description": "Il attend le moment d’évoluer. À ce stade, il ne peut que durcir, restant immobile pour éviter les attaques.",
        "sprite_path": "images/sprites/11.gif",
        "footprint_path": "images/footprints/11.png",
        "cry_path": "sounds/cries/11.ogg",
    },
    "012": {
        "name": "Papilusion",
        "types": ["insecte", "vol"],
        "size": "1.1",
        "weight": "32.0",
        "species": "Pokémon Papillon",
        "description": "En combat, il bat des ailes à grande vitesse pour libérer une poussière très toxique dans les airs.",
        "sprite_path": "images/sprites/12.gif",
        "footprint_path": "images/footprints/12.png",
        "cry_path": "sounds/cries/12.ogg",
    },
    "013": {
        "name": "Aspicot",
        "types": ["insecte", "poison"],
        "size": "0.3",
        "weight": "3.2",
        "species": "Pokémon Insectopic",
        "description": "Fais attention à l’aiguillon pointu sur sa tête. Il se cache dans les herbes pour manger des feuilles.",
        "sprite_path": "images/sprites/13.gif",
        "footprint_path": "images/footprints/13.png",
        "cry_path": "sounds/cries/13.ogg",
    },
    "014": {
        "name": "Coconfort",
        "types": ["insecte", "poison"],
        "size": "0.6",
        "weight": "10.0",
        "species": "Pokémon Cocon",
        "description": "Il ne peut bouger que très légèrement. Lorsqu’il est en danger, il peut ressortir son aiguillon et empoisonner l’ennemi.",
        "sprite_path": "images/sprites/14.gif",
        "footprint_path": "images/footprints/14.png",
        "cry_path": "sounds/cries/14.ogg",
    },
    "015": {
        "name": "Dardargnan",
        "types": ["insecte", "poison"],
        "size": "1.0",
        "weight": "29.5",
        "species": "Pokémon Guêpe",
        "description": "Il a trois aiguillons empoisonnés sur ses pattes avant et sa queue. Ils servent à piquer son ennemi encore et encore.",
        "sprite_path": "images/sprites/15.gif",
        "footprint_path": "images/footprints/15.png",
        "cry_path": "sounds/cries/15.ogg",
    },
    "016": {
        "name": "Roucool",
        "types": ["normal", "vol"],
        "size": "0.3",
        "weight": "1.8",
        "species": "Pokémon Petit Oiseau",
        "description": "Très docile. S’il est attaqué, il soulève souvent du sable pour se protéger plutôt que d’attaquer.",
        "sprite_path": "images/sprites/16.gif",
        "footprint_path": "images/footprints/16.png",
        "cry_path": "sounds/cries/16.ogg",
    },
    "017": {
        "name": "Roucoups",
        "types": ["normal", "vol"],
        "size": "1.1",
        "weight": "30.0",
        "species": "Pokémon Oiseau",
        "description": "Ce Pokémon est plein de vitalité. Il vole constamment autour de son grand territoire à la recherche de proies.",
        "sprite_path": "images/sprites/17.gif",
        "footprint_path": "images/footprints/17.png",
        "cry_path": "sounds/cries/17.ogg",
    },
    "018": {
        "name": "Roucarnage",
        "types": ["normal", "vol"],
        "size": "1.5",
        "weight": "39.5",
        "species": "Pokémon Oiseau",
        "description": "Il vole à une vitesse équivalente à Mach 2, à la recherche de proies. Ses grandes serres sont redoutées comme armes féroces.",
        "sprite_path": "images/sprites/18.gif",
        "footprint_path": "images/footprints/18.png",
        "cry_path": "sounds/cries/18.ogg",
    },
    "019": {
        "name": "Rattata",
        "types": ["normal"],
        "size": "0.3",
        "weight": "3.5",
        "species": "Pokémon Souris",
        "description": "Il mâche n’importe quoi avec ses dents pointues. Si vous en voyez un, il y en a sûrement beaucoup d’autres dans les environs.",
        "sprite_path": "images/sprites/19.gif",
        "footprint_path": "images/footprints/19.png",
        "cry_path": "sounds/cries/19.ogg",
    },
    "020": {
        "name": "Rattatac",
        "types": ["normal"],
        "size": "0.7",
        "weight": "18.5",
        "species": "Pokémon Souris",
        "description": "Ses pattes arrière sont palmées. Elles agissent comme des nageoires pour nager dans les rivières et chasser des proies.",
        "sprite_path": "images/sprites/20.gif",
        "footprint_path": "images/footprints/20.png",
        "cry_path": "sounds/cries/20.ogg",
    },
        "021": {
        "name": "Piafabec",
        "types": ["normal", "vol"],
        "size": "0.3",
        "weight": "2.0",
        "species": "Pokémon Petit Oiseau",
        "description": "Inapte à voler haut. Cependant, il peut voler rapidement autour de son territoire pour le protéger.",
        "sprite_path": "images/sprites/21.gif",
        "footprint_path": "images/footprints/21.png",
        "cry_path": "sounds/cries/21.ogg",
    },
    "022": {
        "name": "Rapasdepic",
        "types": ["normal", "vol"],
        "size": "1.2",
        "weight": "38.0",
        "species": "Pokémon Bec",
        "description": "Un Pokémon très ancien. S’il sent le danger, il s’envole instantanément très haut.",
        "sprite_path": "images/sprites/22.gif",
        "footprint_path": "images/footprints/22.png",
        "cry_path": "sounds/cries/22.ogg",
    },
    "023": {
        "name": "Abo",
        "types": ["poison"],
        "size": "2.0",
        "weight": "6.9",
        "species": "Pokémon Serpent",
        "description": "Plus il vieillit, plus il grandit. La nuit, il s’enroule autour des branches pour se reposer.",
        "sprite_path": "images/sprites/23.gif",
        "footprint_path": "images/footprints/23.png",
        "cry_path": "sounds/cries/23.ogg",
    },
    "024": {
        "name": "Arbok",
        "types": ["poison"],
        "size": "3.5",
        "weight": "65.0",
        "species": "Pokémon Cobra",
        "description": "Les motifs effrayants sur son ventre ont été étudiés. Six variations ont été confirmées.",
        "sprite_path": "images/sprites/24.gif",
        "footprint_path": "images/footprints/24.png",
        "cry_path": "sounds/cries/24.ogg",
    },
    "025": {
        "name": "Pikachu",
        "types": ["électrik"],
        "size": "0.4",
        "weight": "6.0",
        "species": "Pokémon Souris",
        "description": "Les Pikachu capables de générer de puissantes décharges ont des sacs jugulaires extra-souples et extensibles.",
        "sprite_path": "images/sprites/25.gif",
        "footprint_path": "images/footprints/25.png",
        "cry_path": "sounds/cries/25.ogg",
    },
    "026": {
        "name": "Raichu",
        "types": ["électrik"],
        "size": "0.8",
        "weight": "30.0",
        "species": "Pokémon Souris",
        "description": "Sa longue queue sert de mise à la terre pour se protéger de sa propre haute tension.",
        "sprite_path": "images/sprites/26.gif",
        "footprint_path": "images/footprints/26.png",
        "cry_path": "sounds/cries/26.ogg",
    },
    "027": {
        "name": "Sabelette",
        "types": ["sol"],
        "size": "0.6",
        "weight": "12.0",
        "species": "Pokémon Souris",
        "description": "Il adore se rouler dans le sable sec. En faisant cela, il se débarrasse de la saleté et de l’humidité collant à son corps.",
        "sprite_path": "images/sprites/27.gif",
        "footprint_path": "images/footprints/27.png",
        "cry_path": "sounds/cries/27.ogg",
    },
    "028": {
        "name": "Sablaireau",
        "types": ["sol"],
        "size": "1.0",
        "weight": "29.5",
        "species": "Pokémon Souris",
        "description": "Plus l’endroit où vit Sablaireau est sec, plus ses piquants sont durs et lisses au toucher.",
        "sprite_path": "images/sprites/28.gif",
        "footprint_path": "images/footprints/28.png",
        "cry_path": "sounds/cries/28.ogg",
    },
    "029": {
        "name": "Nidoran♀",
        "types": ["poison"],
        "size": "0.4",
        "weight": "7.0",
        "species": "Pokémon Aiguillon",
        "description": "Les femelles sont plus sensibles aux odeurs que les mâles. En cherchant de la nourriture, elles utilisent leurs moustaches pour vérifier la direction du vent et rester sous le vent des prédateurs.",
        "sprite_path": "images/sprites/29.gif",
        "footprint_path": "images/footprints/29.png",
        "cry_path": "sounds/cries/29.ogg",
    },
    "030": {
        "name": "Nidorina",
        "types": ["poison"],
        "size": "0.8",
        "weight": "20.0",
        "species": "Pokémon Aiguillon",
        "description": "La corne sur sa tête s’est atrophiée. On pense que cela se produit pour que les enfants de Nidorina ne se fassent pas piquer en se nourrissant.",
        "sprite_path": "images/sprites/30.gif",
        "footprint_path": "images/footprints/30.png",
        "cry_path": "sounds/cries/30.ogg",
    },
    "031": {
        "name": "Nidoqueen",
        "types": ["poison", "sol"],
        "size": "1.3",
        "weight": "60.0",
        "species": "Pokémon Perceur",
        "description": "Nidoqueen est plus forte en défense qu’en attaque. Avec ses écailles comme armure, elle protège ses enfants de toute attaque.",
        "sprite_path": "images/sprites/31.gif",
        "footprint_path": "images/footprints/31.png",
        "cry_path": "sounds/cries/31.ogg",
    },
    "032": {
        "name": "Nidoran♂",
        "types": ["poison"],
        "size": "0.5",
        "weight": "9.0",
        "species": "Pokémon Aiguillon",
        "description": "La corne sur le front du Nidoran mâle contient un poison puissant. C’est un Pokémon très prudent, toujours à l’écoute avec ses grandes oreilles.",
        "sprite_path": "images/sprites/32.gif",
        "footprint_path": "images/footprints/32.png",
        "cry_path": "sounds/cries/32.ogg",
    },
    "033": {
        "name": "Nidorino",
        "types": ["poison"],
        "size": "0.9",
        "weight": "19.5",
        "species": "Pokémon Aiguillon",
        "description": "Avec une corne plus dure que le diamant, ce Pokémon brise les rochers en cherchant une Pierre Lune.",
        "sprite_path": "images/sprites/33.gif",
        "footprint_path": "images/footprints/33.png",
        "cry_path": "sounds/cries/33.ogg",
    },
    "034": {
        "name": "Nidoking",
        "types": ["poison", "sol"],
        "size": "1.4",
        "weight": "62.0",
        "species": "Pokémon Perceur",
        "description": "Quand il se déchaîne, il est impossible de le contrôler. Mais en présence d’une Nidoqueen qu’il connaît depuis longtemps, il se calme.",
        "sprite_path": "images/sprites/34.gif",
        "footprint_path": "images/footprints/34.png",
        "cry_path": "sounds/cries/34.ogg",
    },
    "035": {
        "name": "Mélofée",
        "types": ["fée"],
        "size": "0.6",
        "weight": "7.5",
        "species": "Pokémon Étoile",
        "description": "On dit que le bonheur vient à ceux qui voient un groupe de Mélofées danser sous une pleine lune.",
        "sprite_path": "images/sprites/35.gif",
        "footprint_path": "images/footprints/35.png",
        "cry_path": "sounds/cries/35.ogg",
    },
    "036": {
        "name": "Mélodelfe",
        "types": ["fée"],
        "size": "1.3",
        "weight": "40.0",
        "species": "Pokémon Étoile",
        "description": "C’est un Pokémon timide rarement vu. Il s’enfuit à la seconde où il sent des humains.",
        "sprite_path": "images/sprites/36.gif",
        "footprint_path": "images/footprints/36.png",
        "cry_path": "sounds/cries/36.ogg",
    },
    "037": {
        "name": "Goupix",
        "types": ["feu"],
        "size": "0.6",
        "weight": "9.9",
        "species": "Pokémon Renard",
        "description": "Quand il est jeune, il a six belles queues. En grandissant, plusieurs nouvelles queues poussent.",
        "sprite_path": "images/sprites/37.gif",
        "footprint_path": "images/footprints/37.png",
        "cry_path": "sounds/cries/37.ogg",
    },
    "038": {
        "name": "Feunard",
        "types": ["feu"],
        "size": "1.1",
        "weight": "19.9",
        "species": "Pokémon Renard",
        "description": "On dit qu’il vit 1 000 ans, et chacune de ses queues est chargée de pouvoirs surnaturels.",
        "sprite_path": "images/sprites/38.gif",
        "footprint_path": "images/footprints/38.png",
        "cry_path": "sounds/cries/38.ogg",
    },
    "039": {
        "name": "Rondoudou",
        "types": ["normal", "fée"],
        "size": "0.5",
        "weight": "5.5",
        "species": "Pokémon Ballon",
        "description": "Rondoudou a une capacité pulmonaire exceptionnelle. Il ne cesse pas de chanter ses berceuses jusqu’à ce que ses adversaires s’endorment.",
        "sprite_path": "images/sprites/39.gif",
        "footprint_path": "images/footprints/39.png",
        "cry_path": "sounds/cries/39.ogg",
    },
    "040": {
        "name": "Grodoudou",
        "types": ["normal", "fée"],
        "size": "1.0",
        "weight": "12.0",
        "species": "Pokémon Ballon",
        "description": "Plus il inspire d’air, plus il gonfle. Si ses adversaires le surprennent de mauvaise humeur, il s’enfle pour les intimider.",
        "sprite_path": "images/sprites/40.gif",
        "footprint_path": "images/footprints/40.png",
        "cry_path": "sounds/cries/40.ogg",
    },
    "041": {
        "name": "Nosferapti",
        "types": ["poison", "vol"],
        "size": "0.8",
        "weight": "7.5",
        "species": "Pokémon Chauve-Souris",
        "description": "Il vole à la recherche de proies la nuit et peut infliger un poison mortel avec ses crocs.",
        "sprite_path": "images/sprites/41.gif",
        "footprint_path": "images/footprints/41.png",
        "cry_path": "sounds/cries/41.ogg",
    },
    "042": {
        "name": "Nosferalto",
        "types": ["poison", "vol"],
        "size": "1.6",
        "weight": "55.0",
        "species": "Pokémon Chauve-Souris",
        "description": "Il plane silencieusement et attaque ses proies sans qu’elles puissent le voir venir.",
        "sprite_path": "images/sprites/42.gif",
        "footprint_path": "images/footprints/42.png",
        "cry_path": "sounds/cries/42.ogg",
    },
    "043": {
        "name": "Mystherbe",
        "types": ["plante", "poison"],
        "size": "0.5",
        "weight": "6.4",
        "species": "Pokémon Graine",
        "description": "Les deux feuilles sur sa tête ont un parfum unique qui attire ses proies.",
        "sprite_path": "images/sprites/43.gif",
        "footprint_path": "images/footprints/43.png",
        "cry_path": "sounds/cries/43.ogg",
    },
    "044": {
        "name": "Ortide",
        "types": ["plante", "poison"],
        "size": "0.7",
        "weight": "13.0",
        "species": "Pokémon Graine",
        "description": "Il utilise ses feuilles pour capturer les insectes et les digérer avec ses enzymes.",
        "sprite_path": "images/sprites/44.gif",
        "footprint_path": "images/footprints/44.png",
        "cry_path": "sounds/cries/44.ogg",
    },
    "045": {
        "name": "Rafflesia",
        "types": ["plante", "poison"],
        "size": "1.2",
        "weight": "54.0",
        "species": "Pokémon Fleur",
        "description": "La grande fleur sur son dos émet un parfum très puissant qui attire les insectes pour se nourrir.",
        "sprite_path": "images/sprites/45.gif",
        "footprint_path": "images/footprints/45.png",
        "cry_path": "sounds/cries/45.ogg",
    },
    "046": {
        "name": "Paras",
        "types": ["insecte", "plante"],
        "size": "0.3",
        "weight": "5.4",
        "species": "Pokémon Champignon",
        "description": "Les champignons sur son dos absorbent les nutriments de Paras pour se développer.",
        "sprite_path": "images/sprites/46.gif",
        "footprint_path": "images/footprints/46.png",
        "cry_path": "sounds/cries/46.ogg",
    },
    "047": {
        "name": "Parasect",
        "types": ["insecte", "plante"],
        "size": "1.0",
        "weight": "29.5",
        "species": "Pokémon Champignon",
        "description": "Le champignon sur son dos a pris le contrôle de son corps. Il se déplace lentement en fonction de lui.",
        "sprite_path": "images/sprites/47.gif",
        "footprint_path": "images/footprints/47.png",
        "cry_path": "sounds/cries/47.ogg",
    },
    "048": {
        "name": "Mimitoss",
        "types": ["insecte", "poison"],
        "size": "0.8",
        "weight": "12.5",
        "species": "Pokémon Insecte",
        "description": "Ses yeux rouges projettent des toxines qui paralysent les ennemis et les insectes de taille moyenne.",
        "sprite_path": "images/sprites/48.gif",
        "footprint_path": "images/footprints/48.png",
        "cry_path": "sounds/cries/48.ogg",
    },
    "049": {
        "name": "Aéromite",
        "types": ["insecte", "poison"],
        "size": "1.2",
        "weight": "32.8",
        "species": "Pokémon Insecte",
        "description": "Sa vitesse de vol est étonnante. Il attaque les proies et les Pokémon ennemis avec ses spores toxiques.",
        "sprite_path": "images/sprites/49.gif",
        "footprint_path": "images/footprints/49.png",
        "cry_path": "sounds/cries/49.ogg",
    },
    "050": {
        "name": "Taupiqueur",
        "types": ["sol"],
        "size": "0.5",
        "weight": "15.0",
        "species": "Pokémon Taupe",
        "description": "Il creuse rapidement des tunnels souterrains et émerge seulement pour se nourrir ou se battre.",
        "sprite_path": "images/sprites/50.gif",
        "footprint_path": "images/footprints/50.png",
        "cry_path": "sounds/cries/50.ogg",
    },
    "051": {
        "name": "Triopikeur",
        "types": ["sol"],
        "size": "1.1",
        "weight": "32.5",
        "species": "Pokémon Taupe",
        "description": "Avec ses trois nez, il peut détecter les vibrations dans le sol pour localiser les proies ou le danger.",
        "sprite_path": "images/sprites/51.gif",
        "footprint_path": "images/footprints/51.png",
        "cry_path": "sounds/cries/51.ogg",
    },
    "052": {
        "name": "Miaouss",
        "types": ["normal"],
        "size": "0.4",
        "weight": "4.2",
        "species": "Pokémon Chat",
        "description": "Il adore voler les objets brillants et sa grande agilité lui permet de s’échapper rapidement.",
        "sprite_path": "images/sprites/52.gif",
        "footprint_path": "images/footprints/52.png",
        "cry_path": "sounds/cries/52.ogg",
    },
    "053": {
        "name": "Persian",
        "types": ["normal"],
        "size": "1.0",
        "weight": "32.0",
        "species": "Pokémon Chat",
        "description": "Il est très élégant et agile. Les guerriers de la haute société le prennent souvent comme animal de compagnie.",
        "sprite_path": "images/sprites/53.gif",
        "footprint_path": "images/footprints/53.png",
        "cry_path": "sounds/cries/53.ogg",
    },
    "054": {
        "name": "Psykokwak",
        "types": ["eau"],
        "size": "0.8",
        "weight": "19.6",
        "species": "Pokémon Canard",
        "description": "Il souffre constamment de maux de tête, et quand ils s’intensifient, il libère une puissante onde psychique.",
        "sprite_path": "images/sprites/54.gif",
        "footprint_path": "images/footprints/54.png",
        "cry_path": "sounds/cries/54.ogg",
    },
    "055": {
        "name": "Akwakwak",
        "types": ["eau"],
        "size": "1.6",
        "weight": "76.6",
        "species": "Pokémon Canard",
        "description": "Son bec peut libérer une énergie psychique dévastatrice quand ses maux de tête deviennent intenses.",
        "sprite_path": "images/sprites/55.gif",
        "footprint_path": "images/footprints/55.png",
        "cry_path": "sounds/cries/55.ogg",
    },
    "056": {
        "name": "Férosinge",
        "types": ["combat"],
        "size": "0.5",
        "weight": "30.0",
        "species": "Pokémon Singe",
        "description": "Il se met en colère très facilement. Une fois énervé, il frappe tout ce qui bouge avec ses poings puissants.",
        "sprite_path": "images/sprites/56.gif",
        "footprint_path": "images/footprints/56.png",
        "cry_path": "sounds/cries/56.ogg",
    },
    "057": {
        "name": "Colossinge",
        "types": ["combat"],
        "size": "1.2",
        "weight": "52.0",
        "species": "Pokémon Singe",
        "description": "Sa puissance de frappe est légendaire. Il peut facilement renverser des arbres et creuser des trous avec ses poings.",
        "sprite_path": "images/sprites/57.gif",
        "footprint_path": "images/footprints/57.png",
        "cry_path": "sounds/cries/57.ogg",
    },
    "058": {
        "name": "Caninos",
        "types": ["feu"],
        "size": "0.7",
        "weight": "19.0",
        "species": "Pokémon Chiot",
        "description": "Il a une flamme vive sur sa queue qui s’agite selon son humeur. Plus la flamme est vive, plus il est en forme.",
        "sprite_path": "images/sprites/58.gif",
        "footprint_path": "images/footprints/58.png",
        "cry_path": "sounds/cries/58.ogg",
    },
    "059": {
        "name": "Arcanin",
        "types": ["feu"],
        "size": "1.9",
        "weight": "155.0",
        "species": "Pokémon Légendaire",
        "description": "Il court à une vitesse fulgurante. Même les voitures ne peuvent pas le rattraper sur de longues distances.",
        "sprite_path": "images/sprites/59.gif",
        "footprint_path": "images/footprints/59.png",
        "cry_path": "sounds/cries/59.ogg",
    },
    "060": {
        "name": "Ptitard",
        "types": ["eau"],
        "size": "0.3",
        "weight": "4.0",
        "species": "Pokémon Grenouille",
        "description": "Il vit près de l’eau et se déplace lentement. Son cri aigu alerte ses amis en cas de danger.",
        "sprite_path": "images/sprites/60.gif",
        "footprint_path": "images/footprints/60.png",
        "cry_path": "sounds/cries/60.ogg",
    },
    "061": {
        "name": "Têtarte",
        "types": ["eau"],
        "size": "0.5",
        "weight": "9.0",
        "species": "Pokémon Grenouille",
        "description": "La boule sur sa tête contient un liquide mystérieux qui peut amplifier ses pouvoirs.",
        "sprite_path": "images/sprites/61.gif",
        "footprint_path": "images/footprints/61.png",
        "cry_path": "sounds/cries/61.ogg",
    },
    "062": {
        "name": "Tartard",
        "types": ["eau", "combat"],
        "size": "1.6",
        "weight": "40.0",
        "species": "Pokémon Grenouille",
        "description": "Son corps musclé et ses jambes puissantes lui permettent de délivrer des coups d’une force extraordinaire.",
        "sprite_path": "images/sprites/62.gif",
        "footprint_path": "images/footprints/62.png",
        "cry_path": "sounds/cries/62.ogg",
    },
    "063": {
        "name": "Abra",
        "types": ["psy"],
        "size": "0.9",
        "weight": "19.5",
        "species": "Pokémon Psi",
        "description": "Il passe la plupart de son temps à dormir. S’il est menacé, il se téléporte instantanément pour fuir.",
        "sprite_path": "images/sprites/63.gif",
        "footprint_path": "images/footprints/63.png",
        "cry_path": "sounds/cries/63.ogg",
    },
    "064": {
        "name": "Kadabra",
        "types": ["psy"],
        "size": "1.3",
        "weight": "56.5",
        "species": "Pokémon Psi",
        "description": "Il maîtrise des pouvoirs psychiques puissants et peut bouger des objets par la force de l’esprit.",
        "sprite_path": "images/sprites/64.gif",
        "footprint_path": "images/footprints/64.png",
        "cry_path": "sounds/cries/64.ogg",
    },
    "065": {
        "name": "Alakazam",
        "types": ["psy"],
        "size": "1.5",
        "weight": "48.0",
        "species": "Pokémon Psi",
        "description": "Son quotient intellectuel est si élevé qu’il peut résoudre n’importe quel problème. Ses pouvoirs psychiques sont exceptionnels.",
        "sprite_path": "images/sprites/65.gif",
        "footprint_path": "images/footprints/65.png",
        "cry_path": "sounds/cries/65.ogg",
    },
    "066": {
        "name": "Machoc",
        "types": ["combat"],
        "size": "0.8",
        "weight": "19.5",
        "species": "Pokémon Super Force",
        "description": "Malgré sa petite taille, il possède une force phénoménale et adore s’entraîner pour devenir encore plus fort.",
        "sprite_path": "images/sprites/66.gif",
        "footprint_path": "images/footprints/66.png",
        "cry_path": "sounds/cries/66.ogg",
    },
    "067": {
        "name": "Machopeur",
        "types": ["combat"],
        "size": "1.5",
        "weight": "70.5",
        "species": "Pokémon Super Force",
        "description": "Il adore les combats physiques. Sa force brute lui permet de soulever facilement de lourdes charges.",
        "sprite_path": "images/sprites/67.gif",
        "footprint_path": "images/footprints/67.png",
        "cry_path": "sounds/cries/67.ogg",
    },
    "068": {
        "name": "Mackogneur",
        "types": ["combat"],
        "size": "1.6",
        "weight": "130.0",
        "species": "Pokémon Super Force",
        "description": "C’est un véritable champion de combat. Il peut détruire des rochers et des arbres d’un seul coup de poing.",
        "sprite_path": "images/sprites/68.gif",
        "footprint_path": "images/footprints/68.png",
        "cry_path": "sounds/cries/68.ogg",
    },
    "069": {
        "name": "Chétiflor",
        "types": ["plante", "poison"],
        "size": "0.4",
        "weight": "4.0",
        "species": "Pokémon Plante",
        "description": "La fleur sur sa tête absorbe les rayons du soleil et libère des spores pour se défendre.",
        "sprite_path": "images/sprites/69.gif",
        "footprint_path": "images/footprints/69.png",
        "cry_path": "sounds/cries/69.ogg",
    },
    "070": {
        "name": "Boustiflor",
        "types": ["plante", "poison"],
        "size": "0.8",
        "weight": "15.2",
        "species": "Pokémon Plante",
        "description": "Ses crochets et ses feuilles peuvent trancher comme des lames, et il repousse ses ennemis avec des spores toxiques.",
        "sprite_path": "images/sprites/70.gif",
        "footprint_path": "images/footprints/70.png",
        "cry_path": "sounds/cries/70.ogg",
    },
    "071": {
        "name": "Empiflor",
        "types": ["plante", "poison"],
        "size": "1.7",
        "weight": "100.0",
        "species": "Pokémon Plante",
        "description": "Sa grande fleur absorbe l’énergie solaire pour lancer des attaques puissantes et épuiser ses adversaires.",
        "sprite_path": "images/sprites/71.gif",
        "footprint_path": "images/footprints/71.png",
        "cry_path": "sounds/cries/71.ogg",
    },
    "072": {
        "name": "Tentacool",
        "types": ["eau", "poison"],
        "size": "0.9",
        "weight": "45.5",
        "species": "Pokémon Méduse",
        "description": "Ses tentacules contiennent du poison capable de paralyser ses ennemis. Il flotte dans l’eau à la recherche de proies.",
        "sprite_path": "images/sprites/72.gif",
        "footprint_path": "images/footprints/72.png",
        "cry_path": "sounds/cries/72.ogg",
    },
    "073": {
        "name": "Tentacruel",
        "types": ["eau", "poison"],
        "size": "1.6",
        "weight": "55.0",
        "species": "Pokémon Méduse",
        "description": "Ses nombreux tentacules peuvent encercler et neutraliser ses ennemis. Son poison est extrêmement puissant.",
        "sprite_path": "images/sprites/73.gif",
        "footprint_path": "images/footprints/73.png",
        "cry_path": "sounds/cries/73.ogg",
    },
    "074": {
        "name": "Racaillou",
        "types": ["roche", "sol"],
        "size": "0.4",
        "weight": "20.0",
        "species": "Pokémon Roche",
        "description": "Il se cache dans les montagnes et utilise sa dure carapace pour se protéger des attaques.",
        "sprite_path": "images/sprites/74.gif",
        "footprint_path": "images/footprints/74.png",
        "cry_path": "sounds/cries/74.ogg",
    },
    "075": {
        "name": "Gravalanch",
        "types": ["roche", "sol"],
        "size": "1.0",
        "weight": "105.0",
        "species": "Pokémon Roche",
        "description": "Il roule sur ses ennemis pour les écraser, utilisant sa lourde masse de pierre pour attaquer.",
        "sprite_path": "images/sprites/75.gif",
        "footprint_path": "images/footprints/75.png",
        "cry_path": "sounds/cries/75.ogg",
    },
    "076": {
        "name": "Grolem",
        "types": ["roche", "sol"],
        "size": "1.4",
        "weight": "300.0",
        "species": "Pokémon Roche",
        "description": "Sa peau de pierre le rend presque invincible. Il peut rouler à grande vitesse pour foncer sur ses ennemis.",
        "sprite_path": "images/sprites/76.gif",
        "footprint_path": "images/footprints/76.png",
        "cry_path": "sounds/cries/76.ogg",
    },
    "077": {
        "name": "Ponyta",
        "types": ["feu"],
        "size": "1.0",
        "weight": "30.0",
        "species": "Pokémon Cheval",
        "description": "La flamme sur sa crinière brûle toujours vivement. Il peut courir à des vitesses étonnantes.",
        "sprite_path": "images/sprites/77.gif",
        "footprint_path": "images/footprints/77.png",
        "cry_path": "sounds/cries/77.ogg",
    },
    "078": {
        "name": "Galopa",
        "types": ["feu"],
        "size": "1.7",
        "weight": "95.0",
        "species": "Pokémon Cheval",
        "description": "Sa crinière et sa queue sont des flammes ardentes. Il est capable de courir plus vite que n’importe quel autre Pokémon.",
        "sprite_path": "images/sprites/78.gif",
        "footprint_path": "images/footprints/78.png",
        "cry_path": "sounds/cries/78.ogg",
    },
    "079": {
        "name": "Ramoloss",
        "types": ["eau", "psy"],
        "size": "1.2",
        "weight": "36.0",
        "species": "Pokémon Lenteur",
        "description": "Toujours dans un état de rêverie, il est incroyablement lent mais peut utiliser ses pouvoirs psychiques malgré tout.",
        "sprite_path": "images/sprites/79.gif",
        "footprint_path": "images/footprints/79.png",
        "cry_path": "sounds/cries/79.ogg",
    },
    "080": {
        "name": "Flagadoss",
        "types": ["eau", "psy"],
        "size": "1.7",
        "weight": "76.6",
        "species": "Pokémon Lenteur",
        "description": "Il est extrêmement lent et oublie souvent ce qui se passe autour de lui. Ses pouvoirs psychiques restent néanmoins puissants.",
        "sprite_path": "images/sprites/80.gif",
        "footprint_path": "images/footprints/80.png",
        "cry_path": "sounds/cries/80.ogg",
    },
    "081": {
        "name": "Magnéti",
        "types": ["électrik", "acier"],
        "size": "0.3",
        "weight": "6.0",
        "species": "Pokémon Aimant",
        "description": "Il se déplace en flottant grâce à son puissant champ magnétique et attire les objets métalliques autour de lui.",
        "sprite_path": "images/sprites/81.gif",
        "footprint_path": "images/footprints/81.png",
        "cry_path": "sounds/cries/81.ogg",
    },
    "082": {
        "name": "Magnéton",
        "types": ["électrik", "acier"],
        "size": "1.0",
        "weight": "60.0",
        "species": "Pokémon Aimant",
        "description": "Il est formé de trois Magnéti réunis. Il génère un champ magnétique extrêmement puissant.",
        "sprite_path": "images/sprites/82.gif",
        "footprint_path": "images/footprints/82.png",
        "cry_path": "sounds/cries/82.ogg",
    },
    "083": {
        "name": "Canarticho",
        "types": ["normal", "vol"],
        "size": "1.5",
        "weight": "78.2",
        "species": "Pokémon Canard",
        "description": "Son bec peut infliger des coups puissants. Il est très agile malgré sa taille.",
        "sprite_path": "images/sprites/83.gif",
        "footprint_path": "images/footprints/83.png",
        "cry_path": "sounds/cries/83.ogg",
    },
    "084": {
        "name": "Doduo",
        "types": ["normal", "vol"],
        "size": "1.4",
        "weight": "39.2",
        "species": "Pokémon Oiseau",
        "description": "Il possède deux têtes et peut courir extrêmement vite pour échapper aux prédateurs.",
        "sprite_path": "images/sprites/84.gif",
        "footprint_path": "images/footprints/84.png",
        "cry_path": "sounds/cries/84.ogg",
    },
    "085": {
        "name": "Dodrio",
        "types": ["normal", "vol"],
        "size": "1.8",
        "weight": "85.2",
        "species": "Pokémon Oiseau",
        "description": "Il possède trois têtes et peut courir à grande vitesse. Ses attaques sont coordonnées entre ses trois cerveaux.",
        "sprite_path": "images/sprites/85.gif",
        "footprint_path": "images/footprints/85.png",
        "cry_path": "sounds/cries/85.ogg",
    },
    "086": {
        "name": "Otaria",
        "types": ["eau"],
        "size": "1.1",
        "weight": "60.0",
        "species": "Pokémon Lion de Mer",
        "description": "Elle aime jouer dans l’eau. Son corps est puissant et lui permet de nager rapidement pour échapper aux prédateurs.",
        "sprite_path": "images/sprites/86.gif",
        "footprint_path": "images/footprints/86.png",
        "cry_path": "sounds/cries/86.ogg",
    },
    "087": {
        "name": "Lamantine",
        "types": ["eau", "glace"],
        "size": "2.5",
        "weight": "220.0",
        "species": "Pokémon Sirène",
        "description": "Elle nage paisiblement dans les océans. Sa force physique est surprenante malgré son apparence douce.",
        "sprite_path": "images/sprites/87.gif",
        "footprint_path": "images/footprints/87.png",
        "cry_path": "sounds/cries/87.ogg",
    },
    "088": {
        "name": "Tadmorv",
        "types": ["poison"],
        "size": "0.8",
        "weight": "30.0",
        "species": "Pokémon Boue",
        "description": "Son corps est entièrement constitué de boue toxique. Il s’étale sur le sol pour attaquer ou se défendre.",
        "sprite_path": "images/sprites/88.gif",
        "footprint_path": "images/footprints/88.png",
        "cry_path": "sounds/cries/88.ogg",
    },
    "089": {
        "name": "Grotadmorv",
        "types": ["poison"],
        "size": "1.2",
        "weight": "60.0",
        "species": "Pokémon Boue",
        "description": "Il dégage une odeur extrêmement nauséabonde qui peut paralyser ses ennemis. Son corps est très résistant.",
        "sprite_path": "images/sprites/89.gif",
        "footprint_path": "images/footprints/89.png",
        "cry_path": "sounds/cries/89.ogg",
    },
    "090": {
        "name": "Kokiyas",
        "types": ["eau"],
        "size": "0.3",
        "weight": "5.0",
        "species": "Pokémon Coquillage",
        "description": "Sa coquille est dure et protège ses parties molles. Il se referme dès qu’il est menacé.",
        "sprite_path": "images/sprites/90.gif",
        "footprint_path": "images/footprints/90.png",
        "cry_path": "sounds/cries/90.ogg",
    },
    "091": {
        "name": "Crustabri",
        "types": ["eau", "glace"],
        "size": "1.7",
        "weight": "132.5",
        "species": "Pokémon Coquillage",
        "description": "Sa carapace est extrêmement dure. Ses pinces peuvent broyer la pierre et attraper ses proies.",
        "sprite_path": "images/sprites/91.gif",
        "footprint_path": "images/footprints/91.png",
        "cry_path": "sounds/cries/91.ogg",
    },
    "092": {
        "name": "Fantominus",
        "types": ["spectre", "poison"],
        "size": "1.3",
        "weight": "0.1",
        "species": "Pokémon Fantôme",
        "description": "Il peut passer à travers les murs et émettre un gaz toxique pour effrayer ou affaiblir ses ennemis.",
        "sprite_path": "images/sprites/92.gif",
        "footprint_path": "images/footprints/92.png",
        "cry_path": "sounds/cries/92.ogg",
    },
    "093": {
        "name": "Spectrum",
        "types": ["spectre", "poison"],
        "size": "1.3",
        "weight": "0.1",
        "species": "Pokémon Fantôme",
        "description": "Il est constitué d’énergie spectrale. Il peut disparaître et apparaître à volonté pour effrayer ses proies.",
        "sprite_path": "images/sprites/93.gif",
        "footprint_path": "images/footprints/93.png",
        "cry_path": "sounds/cries/93.ogg",
    },
    "094": {
        "name": "Ectoplasma",
        "types": ["spectre", "poison"],
        "size": "1.5",
        "weight": "40.5",
        "species": "Pokémon Fantôme",
        "description": "Il peut traverser n’importe quel obstacle et libérer des gaz toxiques. Il est redoutable dans les combats.",
        "sprite_path": "images/sprites/94.gif",
        "footprint_path": "images/footprints/94.png",
        "cry_path": "sounds/cries/94.ogg",
    },
    "095": {
        "name": "Onix",
        "types": ["roche", "sol"],
        "size": "8.8",
        "weight": "210.0",
        "species": "Pokémon Serpent de Roche",
        "description": "Un Pokémon énorme fait de roches reliées entre elles. Il peut creuser des tunnels et écraser ses ennemis.",
        "sprite_path": "images/sprites/95.gif",
        "footprint_path": "images/footprints/95.png",
        "cry_path": "sounds/cries/95.ogg",
    },
    "096": {
        "name": "Soporifik",
        "types": ["psy"],
        "size": "1.6",
        "weight": "61.0",
        "species": "Pokémon Hypnose",
        "description": "Il utilise ses pouvoirs psychiques pour endormir ses adversaires et profiter de la situation pour attaquer.",
        "sprite_path": "images/sprites/96.gif",
        "footprint_path": "images/footprints/96.png",
        "cry_path": "sounds/cries/96.ogg",
    },
    "097": {
        "name": "Hypnomade",
        "types": ["psy"],
        "size": "1.6",
        "weight": "75.6",
        "species": "Pokémon Hypnose",
        "description": "Il secoue son pendule pour endormir ses ennemis et les manipuler à sa guise.",
        "sprite_path": "images/sprites/97.gif",
        "footprint_path": "images/footprints/97.png",
        "cry_path": "sounds/cries/97.ogg",
    },
    "098": {
        "name": "Krabby",
        "types": ["eau"],
        "size": "0.4",
        "weight": "6.5",
        "species": "Pokémon Crabe",
        "description": "Ses pinces puissantes peuvent briser les coquilles et la roche. Il se déplace latéralement très vite.",
        "sprite_path": "images/sprites/98.gif",
        "footprint_path": "images/footprints/98.png",
        "cry_path": "sounds/cries/98.ogg",
    },
    "099": {
        "name": "Krabboss",
        "types": ["eau"],
        "size": "1.3",
        "weight": "60.0",
        "species": "Pokémon Crabe",
        "description": "Sa pince droite est beaucoup plus grande et très puissante. Il peut écraser ses proies avec une force incroyable.",
        "sprite_path": "images/sprites/99.gif",
        "footprint_path": "images/footprints/99.png",
        "cry_path": "sounds/cries/99.ogg",
    },
    "100": {
        "name": "Voltorbe",
        "types": ["électrik"],
        "size": "0.5",
        "weight": "10.4",
        "species": "Pokémon Boule",
        "description": "Il ressemble à une Pokéball mais peut exploser à tout moment. Il est très instable et dangereux.",
        "sprite_path": "images/sprites/100.gif",
        "footprint_path": "images/footprints/100.png",
        "cry_path": "sounds/cries/100.ogg",
    },
    "101": {
        "name": "Électrode",
        "types": ["électrik"],
        "size": "1.2",
        "weight": "66.6",
        "species": "Pokémon Boule",
        "description": "Comme Voltorbe, il peut exploser à tout moment. Son corps est entièrement chargé d’électricité.",
        "sprite_path": "images/sprites/101.gif",
        "footprint_path": "images/footprints/101.png",
        "cry_path": "sounds/cries/101.ogg",
    },
    "102": {
        "name": "Noeunoeuf",
        "types": ["plante", "psy"],
        "size": "0.4",
        "weight": "7.5",
        "species": "Pokémon Œuf",
        "description": "Il passe toute sa vie à l’intérieur de son œuf. Ses mouvements sont limités mais il absorbe beaucoup de nutriments.",
        "sprite_path": "images/sprites/102.gif",
        "footprint_path": "images/footprints/102.png",
        "cry_path": "sounds/cries/102.ogg",
    },
    "103": {
        "name": "Noadkoko",
        "types": ["plante", "psy"],
        "size": "2.0",
        "weight": "80.0",
        "species": "Pokémon Palmier",
        "description": "Il porte un grand corps et plusieurs œufs sur sa tête. Les œufs tombent parfois sur ses ennemis.",
        "sprite_path": "images/sprites/103.gif",
        "footprint_path": "images/footprints/103.png",
        "cry_path": "sounds/cries/103.ogg",
    },
    "104": {
        "name": "Osselait",
        "types": ["sol"],
        "size": "0.5",
        "weight": "11.5",
        "species": "Pokémon Os",
        "description": "Son os est dur et solide. Il le mâche pour s’entraîner et pour se défendre.",
        "sprite_path": "images/sprites/104.gif",
        "footprint_path": "images/footprints/104.png",
        "cry_path": "sounds/cries/104.ogg",
    },
    "105": {
        "name": "Ossatueur",
        "types": ["sol"],
        "size": "1.4",
        "weight": "70.5",
        "species": "Pokémon Os",
        "description": "Son os est utilisé comme arme. Il peut le lancer avec précision pour attaquer à distance.",
        "sprite_path": "images/sprites/105.gif",
        "footprint_path": "images/footprints/105.png",
        "cry_path": "sounds/cries/105.ogg",
    },
    "106": {
        "name": "Kicklee",
        "types": ["combat"],
        "size": "1.0",
        "weight": "35.0",
        "species": "Pokémon Coup de Pied",
        "description": "Spécialiste des coups de pied, il peut frapper avec une vitesse incroyable et renverser ses adversaires.",
        "sprite_path": "images/sprites/106.gif",
        "footprint_path": "images/footprints/106.png",
        "cry_path": "sounds/cries/106.ogg",
    },
    "107": {
        "name": "Tygnon",
        "types": ["combat"],
        "size": "1.0",
        "weight": "47.0",
        "species": "Pokémon Poing",
        "description": "Ses poings sont puissants et précis. Il s’entraîne constamment pour augmenter sa force.",
        "sprite_path": "images/sprites/107.gif",
        "footprint_path": "images/footprints/107.png",
        "cry_path": "sounds/cries/107.ogg",
    },
    "108": {
        "name": "Excelangue",
        "types": ["normal"],
        "size": "1.5",
        "weight": "40.0",
        "species": "Pokémon Longue Langue",
        "description": "Sa langue extrêmement longue lui permet d’attaquer et d’attraper des objets à distance.",
        "sprite_path": "images/sprites/108.gif",
        "footprint_path": "images/footprints/108.png",
        "cry_path": "sounds/cries/108.ogg",
    },
    "109": {
        "name": "Smogo",
        "types": ["poison"],
        "size": "0.5",
        "weight": "10.0",
        "species": "Pokémon Gaz",
        "description": "Il libère un gaz toxique pour se défendre. L’inhalation de son nuage peut rendre malade.",
        "sprite_path": "images/sprites/109.gif",
        "footprint_path": "images/footprints/109.png",
        "cry_path": "sounds/cries/109.ogg",
    },
    "110": {
        "name": "Smogogo",
        "types": ["poison"],
        "size": "1.2",
        "weight": "40.0",
        "species": "Pokémon Gaz",
        "description": "Son corps entier produit du gaz toxique. Il peut créer un nuage étouffant pour attaquer.",
        "sprite_path": "images/sprites/110.gif",
        "footprint_path": "images/footprints/110.png",
        "cry_path": "sounds/cries/110.ogg",
    },
    "111": {
        "name": "Rhinocorne",
        "types": ["sol", "roche"],
        "size": "1.0",
        "weight": "115.0",
        "species": "Pokémon Rhinocéros",
        "description": "Son corps lourd et ses cornes lui permettent de charger avec force ses ennemis et écraser tout sur son passage.",
        "sprite_path": "images/sprites/111.gif",
        "footprint_path": "images/footprints/111.png",
        "cry_path": "sounds/cries/111.ogg",
    },
    "112": {
        "name": "Rhinoféros",
        "types": ["sol", "roche"],
        "size": "2.0",
        "weight": "120.0",
        "species": "Pokémon Rhinocéros",
        "description": "Il utilise ses cornes et sa puissance pour détruire tout obstacle. Très résistant, il est redoutable en combat.",
        "sprite_path": "images/sprites/112.gif",
        "footprint_path": "images/footprints/112.png",
        "cry_path": "sounds/cries/112.ogg",
    },
    "113": {
        "name": "Leveinard",
        "types": ["normal"],
        "size": "1.0",
        "weight": "34.6",
        "species": "Pokémon Chance",
        "description": "Il porte un œuf chanceux sur son ventre et apporte la bonne fortune. Il protège son œuf avec soin.",
        "sprite_path": "images/sprites/113.gif",
        "footprint_path": "images/footprints/113.png",
        "cry_path": "sounds/cries/113.ogg",
    },
    "114": {
        "name": "Saquedeneu",
        "types": ["plante"],
        "size": "0.6",
        "weight": "8.5",
        "species": "Pokémon Fleur",
        "description": "Il absorbe la lumière du soleil pour nourrir la fleur sur son dos. Il reste souvent immobile.",
        "sprite_path": "images/sprites/114.gif",
        "footprint_path": "images/footprints/114.png",
        "cry_path": "sounds/cries/114.ogg",
    },
    "115": {
        "name": "Kangourex",
        "types": ["normal"],
        "size": "2.2",
        "weight": "80.0",
        "species": "Pokémon Kangourou",
        "description": "Il transporte son petit dans sa poche ventrale et bondit puissamment pour se défendre ou chasser.",
        "sprite_path": "images/sprites/115.gif",
        "footprint_path": "images/footprints/115.png",
        "cry_path": "sounds/cries/115.ogg",
    },
    "116": {
        "name": "Hypotrempe",
        "types": ["eau"],
        "size": "0.4",
        "weight": "8.0",
        "species": "Pokémon Dragon",
        "description": "Bien que petit, il est agile et vit près des cours d’eau. Ses nageoires sont souples et rapides.",
        "sprite_path": "images/sprites/116.gif",
        "footprint_path": "images/footprints/116.png",
        "cry_path": "sounds/cries/116.ogg",
    },
    "117": {
        "name": "Hypocéan",
        "types": ["eau"],
        "size": "0.8",
        "weight": "16.0",
        "species": "Pokémon Dragon",
        "description": "Il a grandi depuis Hypotrempe. Il nage rapidement et attaque ses proies avec force.",
        "sprite_path": "images/sprites/117.gif",
        "footprint_path": "images/footprints/117.png",
        "cry_path": "sounds/cries/117.ogg",
    },
    "118": {
        "name": "Poissirène",
        "types": ["eau"],
        "size": "0.6",
        "weight": "7.0",
        "species": "Pokémon Sirène",
        "description": "Cette petite sirène est rapide et gracieuse dans l’eau. Son chant attire parfois les prédateurs.",
        "sprite_path": "images/sprites/118.gif",
        "footprint_path": "images/footprints/118.png",
        "cry_path": "sounds/cries/118.ogg",
    },
    "119": {
        "name": "Poissoroy",
        "types": ["eau"],
        "size": "1.5",
        "weight": "61.0",
        "species": "Pokémon Roi",
        "description": "Il règne sur les eaux. Ses nageoires puissantes lui permettent de se déplacer avec rapidité et force.",
        "sprite_path": "images/sprites/119.gif",
        "footprint_path": "images/footprints/119.png",
        "cry_path": "sounds/cries/119.ogg",
    },
    "120": {
        "name": "Stari",
        "types": ["eau"],
        "size": "0.8",
        "weight": "34.5",
        "species": "Pokémon Étoile",
        "description": "Il se déplace lentement sur le fond marin. Ses bras sont fragiles mais très sensibles au toucher.",
        "sprite_path": "images/sprites/120.gif",
        "footprint_path": "images/footprints/120.png",
        "cry_path": "sounds/cries/120.ogg",
    },
    "121": {
        "name": "Staross",
        "types": ["eau", "psy"],
        "size": "1.1",
        "weight": "80.0",
        "species": "Pokémon Étoile",
        "description": "Ce Pokémon étoilé absorbe l’énergie de l’eau et de la lumière pour libérer des ondes puissantes.",
        "sprite_path": "images/sprites/121.gif",
        "footprint_path": "images/footprints/121.png",
        "cry_path": "sounds/cries/121.ogg",
    },
    "122": {
        "name": "M. Mime",
        "types": ["psy", "fée"],
        "size": "1.3",
        "weight": "54.5",
        "species": "Pokémon Barrière",
        "description": "Il mime des actions irréelles pour perturber ses ennemis et crée des barrières invisibles.",
        "sprite_path": "images/sprites/122.gif",
        "footprint_path": "images/footprints/122.png",
        "cry_path": "sounds/cries/122.ogg",
    },
    "123": {
        "name": "Insécateur",
        "types": ["insecte", "vol"],
        "size": "1.5",
        "weight": "56.0",
        "species": "Pokémon Faucheur",
        "description": "Bondissant hors de l’herbe comme un ninja, il lacère sa proie avec ses griffes affûtées.",
        "sprite_path": "images/sprites/123.gif",
        "footprint_path": "images/footprints/123.png",
        "cry_path": "sounds/cries/123.ogg",
    },
    "124": {
        "name": "Lippoutou",
        "types": ["psy", "glace"],
        "size": "1.4",
        "weight": "40.6",
        "species": "Pokémon Silhouette",
        "description": "Ses mouvements ressemblent à une danse gracieuse, mais il frappe avec des attaques glaciales redoutables.",
        "sprite_path": "images/sprites/124.gif",
        "footprint_path": "images/footprints/124.png",
        "cry_path": "sounds/cries/124.ogg",
    },
    "125": {
        "name": "Élektek",
        "types": ["électrik"],
        "size": "1.1",
        "weight": "30.0",
        "species": "Pokémon Électrique",
        "description": "Il provoque souvent des pannes en absorbant l’électricité ambiante et en la relâchant en décharges.",
        "sprite_path": "images/sprites/125.gif",
        "footprint_path": "images/footprints/125.png",
        "cry_path": "sounds/cries/125.ogg",
    },
    "126": {
        "name": "Magmar",
        "types": ["feu"],
        "size": "1.3",
        "weight": "44.5",
        "species": "Pokémon Torche",
        "description": "Né dans des volcans en fusion, son corps est enveloppé de flammes brûlantes et ardentes.",
        "sprite_path": "images/sprites/126.gif",
        "footprint_path": "images/footprints/126.png",
        "cry_path": "sounds/cries/126.ogg",
    },
    "127": {
        "name": "Scarabrute",
        "types": ["insecte"],
        "size": "1.5",
        "weight": "55.0",
        "species": "Pokémon Scarabée",
        "description": "Puissant et agressif, il utilise ses grandes pinces pour écraser ses adversaires.",
        "sprite_path": "images/sprites/127.gif",
        "footprint_path": "images/footprints/127.png",
        "cry_path": "sounds/cries/127.ogg",
    },
    "128": {
        "name": "Tauros",
        "types": ["normal"],
        "size": "1.4",
        "weight": "88.4",
        "species": "Pokémon Taureau",
        "description": "Très agité, il charge à toute vitesse et utilise sa force brute pour renverser tout sur son passage.",
        "sprite_path": "images/sprites/128.gif",
        "footprint_path": "images/footprints/128.png",
        "cry_path": "sounds/cries/128.ogg",
    },
    "129": {
        "name": "Magicarpe",
        "types": ["eau"],
        "size": "0.9",
        "weight": "10.0",
        "species": "Pokémon Poisson",
        "description": "Virtuellement inutile hors de l’eau, il est célèbre pour être l’un des Pokémon les plus faibles.",
        "sprite_path": "images/sprites/129.gif",
        "footprint_path": "images/footprints/129.png",
        "cry_path": "sounds/cries/129.ogg",
    },
    "130": {
        "name": "Léviator",
        "types": ["eau", "vol"],
        "size": "6.5",
        "weight": "235.0",
        "species": "Pokémon Atroce",
        "description": "D’une nature très agressive, il crache des jets d’eau puissants et attaque sans pitié.",
        "sprite_path": "images/sprites/130.gif",
        "footprint_path": "images/footprints/130.png",
        "cry_path": "sounds/cries/130.ogg",
    },
    "131": {
        "name": "Lokhlass",
        "types": ["eau", "glace"],
        "size": "2.5",
        "weight": "220.0",
        "species": "Pokémon Transat",
        "description": "Bon nageur, il transporte les voyageurs sur son dos à travers de longues distances.",
        "sprite_path": "images/sprites/131.gif",
        "footprint_path": "images/footprints/131.png",
        "cry_path": "sounds/cries/131.ogg",
    },
    "132": {
        "name": "Métamorph",
        "types": ["normal"],
        "size": "0.3",
        "weight": "4.0",
        "species": "Pokémon Transformation",
        "description": "Il peut reconstituer sa structure cellulaire pour imiter presque n’importe quel Pokémon.",
        "sprite_path": "images/sprites/132.gif",
        "footprint_path": "images/footprints/132.png",
        "cry_path": "sounds/cries/132.ogg",
    },
    "133": {
        "name": "Évoli",
        "types": ["normal"],
        "size": "0.3",
        "weight": "6.5",
        "species": "Pokémon Évolution",
        "description": "Son corps possède une flexibilité qui lui permet d’évoluer en plusieurs formes différentes.",
        "sprite_path": "images/sprites/133.gif",
        "footprint_path": "images/footprints/133.png",
        "cry_path": "sounds/cries/133.ogg",
    },
    "134": {
        "name": "Aquali",
        "types": ["eau"],
        "size": "1.0",
        "weight": "29.0",
        "species": "Pokémon Bubble Jet",
        "description": "Ses nageoires permettent de nager gracieusement et annoncent parfois l’arrivée de la pluie.",
        "sprite_path": "images/sprites/134.gif",
        "footprint_path": "images/footprints/134.png",
        "cry_path": "sounds/cries/134.ogg",
    },
    "135": {
        "name": "Voltali",
        "types": ["électrik"],
        "size": "0.8",
        "weight": "24.5",
        "species": "Pokémon Éclair",
        "description": "Si on le surprend ou le stimule, ses poils se hérissent comme des aiguilles chargées.",
        "sprite_path": "images/sprites/135.gif",
        "footprint_path": "images/footprints/135.png",
        "cry_path": "sounds/cries/135.ogg",
    },
    "136": {
        "name": "Pyroli",
        "types": ["feu"],
        "size": "0.9",
        "weight": "25.0",
        "species": "Pokémon Flamme",
        "description": "Son corps peut atteindre des températures très élevées lorsqu’il stocke de la chaleur.",
        "sprite_path": "images/sprites/136.gif",
        "footprint_path": "images/footprints/136.png",
        "cry_path": "sounds/cries/136.ogg",
    },
    "137": {
        "name": "Porygon",
        "types": ["normal"],
        "size": "0.8",
        "weight": "36.5",
        "species": "Pokémon Virtuel",
        "description": "Créé par ordinateur, il explore des mondes numériques et s’adapte à différents systèmes.",
        "sprite_path": "images/sprites/137.gif",
        "footprint_path": "images/footprints/137.png",
        "cry_path": "sounds/cries/137.ogg",
    },
    "138": {
        "name": "Amonita",
        "types": ["roche", "eau"],
        "size": "0.4",
        "weight": "7.5",
        "species": "Pokémon Spirale",
        "description": "Ce fossile ancien est devenu un Pokémon vivant après sa restauration.",
        "sprite_path": "images/sprites/138.gif",
        "footprint_path": "images/footprints/138.png",
        "cry_path": "sounds/cries/138.ogg",
    },
    "139": {
        "name": "Amonistar",
        "types": ["roche", "eau"],
        "size": "1.0",
        "weight": "35.0",
        "species": "Pokémon Spirale",
        "description": "Sa grande coquille lui permet de nager lentement et de capturer des proies avec ses tentacules.",
        "sprite_path": "images/sprites/139.gif",
        "footprint_path": "images/footprints/139.png",
        "cry_path": "sounds/cries/139.ogg",
    },
    "140": {
        "name": "Kabuto",
        "types": ["roche", "eau"],
        "size": "0.5",
        "weight": "11.5",
        "species": "Pokémon Coquille",
        "description": "Ce fossile ancien est devenu un Pokémon vivant après sa restauration. Il nage rapidement pour capturer ses proies.",
        "sprite_path": "images/sprites/140.gif",
        "footprint_path": "images/footprints/140.png",
        "cry_path": "sounds/cries/140.ogg",
    },
    "141": {
        "name": "Kabutops",
        "types": ["roche", "eau"],
        "size": "1.3",
        "weight": "40.5",
        "species": "Pokémon Scie",
        "description": "Avec ses bras tranchants, il attaque rapidement ses proies et fend tout obstacle sur son passage.",
        "sprite_path": "images/sprites/141.gif",
        "footprint_path": "images/footprints/141.png",
        "cry_path": "sounds/cries/141.ogg",
    },
    "142": {
        "name": "Ptéra",
        "types": ["roche", "vol"],
        "size": "1.8",
        "weight": "59.0",
        "species": "Pokémon Fossile",
        "description": "Ce Pokémon préhistorique volant domine les cieux et utilise ses serres pour saisir ses proies.",
        "sprite_path": "images/sprites/142.gif",
        "footprint_path": "images/footprints/142.png",
        "cry_path": "sounds/cries/142.ogg",
    },
    "143": {
        "name": "Ronflex",
        "types": ["normal"],
        "size": "2.1",
        "weight": "460.0",
        "species": "Pokémon Gros Dodo",
        "description": "Il dort profondément et peut engloutir tout ce qui se trouve sur son chemin. Il se réveille rarement.",
        "sprite_path": "images/sprites/143.gif",
        "footprint_path": "images/footprints/143.png",
        "cry_path": "sounds/cries/143.ogg",
    },
    "144": {
        "name": "Artikodin",
        "types": ["glace", "vol"],
        "size": "1.7",
        "weight": "55.4",
        "species": "Pokémon Glace",
        "description": "Un oiseau légendaire qui contrôle la glace. Il apporte le froid glacial lorsqu’il vole.",
        "sprite_path": "images/sprites/144.gif",
        "footprint_path": "images/footprints/144.png",
        "cry_path": "sounds/cries/144.ogg",
    },
    "145": {
        "name": "Électhor",
        "types": ["électrik", "vol"],
        "size": "2.0",
        "weight": "60.0",
        "species": "Pokémon Foudre",
        "description": "Cet oiseau légendaire apparaît lors des tempêtes électriques et peut générer d’énormes éclairs.",
        "sprite_path": "images/sprites/145.gif",
        "footprint_path": "images/footprints/145.png",
        "cry_path": "sounds/cries/145.ogg",
    },
    "146": {
        "name": "Sulfura",
        "types": ["feu", "vol"],
        "size": "2.0",
        "weight": "60.0",
        "species": "Pokémon Flamme",
        "description": "Oiseau légendaire du feu, il est entouré de flammes et peut enflammer tout ce qui l’entoure.",
        "sprite_path": "images/sprites/146.gif",
        "footprint_path": "images/footprints/146.png",
        "cry_path": "sounds/cries/146.ogg",
    },
    "147": {
        "name": "Minidraco",
        "types": ["dragon"],
        "size": "0.3",
        "weight": "8.0",
        "species": "Pokémon Dragon",
        "description": "Ce petit dragon est agile et flexible. Il se transforme progressivement en un puissant dragon.",
        "sprite_path": "images/sprites/147.gif",
        "footprint_path": "images/footprints/147.png",
        "cry_path": "sounds/cries/147.ogg",
    },
    "148": {
        "name": "Draco",
        "types": ["dragon"],
        "size": "1.8",
        "weight": "85.0",
        "species": "Pokémon Dragon",
        "description": "Ce dragon à l’allure majestueuse est très puissant et agile dans les airs et sur la terre ferme.",
        "sprite_path": "images/sprites/148.gif",
        "footprint_path": "images/footprints/148.png",
        "cry_path": "sounds/cries/148.ogg",
    },
    "149": {
        "name": "Dracolosse",
        "types": ["dragon", "vol"],
        "size": "2.2",
        "weight": "210.0",
        "species": "Pokémon Dragon",
        "description": "Dragon légendaire combinant puissance et vitesse, capable de détruire tout obstacle grâce à ses ailes et sa force.",
        "sprite_path": "images/sprites/149.gif",
        "footprint_path": "images/footprints/149.png",
        "cry_path": "sounds/cries/149.ogg",
    },
    "150": {
        "name": "Mewtwo",
        "types": ["psy"],
        "size": "2.0",
        "weight": "122.0",
        "species": "Pokémon Génétique",
        "description": "Créé par manipulation génétique, il possède une puissance psychique extraordinaire surpassant tout autre Pokémon.",
        "sprite_path": "images/sprites/150.gif",
        "footprint_path": "images/footprints/150.png",
        "cry_path": "sounds/cries/150.ogg",
    },
    "151": {
        "name": "Mew",
        "types": ["psy"],
        "size": "0.4",
        "weight": "4.0",
        "species": "Pokémon Nouveau",
        "description": "Ce Pokémon mystérieux contient l’ADN de tous les Pokémon et peut apprendre presque toutes les capacités.",
        "sprite_path": "images/sprites/151.gif",
        "footprint_path": "images/footprints/151.png",
        "cry_path": "sounds/cries/151.ogg",
    },
}